# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Starving Dragon
tagline:             'The ravings of a caffeine-depraved programmer'
description:         ''
url:                 http://starvingdragon.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Simon Mansfield
  url:               https://twitter.com/siyfion
  email:             siyfion@gmail.com

# Custom vars
version:             1.0.0
