# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Starving Dragon
tagline:             'The ravings of a caffeine-depraved programmer & gamer'
description:         ''
url:                 http://starvingdragon.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Simon Mansfield
  url:               https://twitter.com/starvingdragon
  email:             the@starvingdragon.com

# Custom vars
version:             1.0.0
